# Generated by Django 6.0 on 2025-12-05 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lezione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inizio', models.DateTimeField(help_text='Giorno e ora della lezione')),
                ('durata_ore', models.IntegerField(default=1, help_text='Durata in ore')),
                ('luogo', models.CharField(choices=[('ONLINE', '💻 Online (Skype/Meet)'), ('MIA_CASA', '🏠 A casa mia (Rufina)'), ('RUFINA_DOMICILIO', '🚗 A domicilio: Rufina / Montebonello / Scopeti (+2€)'), ('PONTASSIEVE_PELAGO', '🚗 A domicilio: Pontassieve / Pelago / S.Francesco (+5€)'), ('DICOMANO', '🚗 A domicilio: Dicomano / Contea / Turicchi (+5€)'), ('SIECI_LONDA', '🚗 A domicilio: Sieci / Londa (+10€)')], default='ONLINE', max_length=30)),
                ('stato', models.CharField(choices=[('RICHIESTA', 'In attesa di conferma'), ('CONFERMATA', 'Confermata'), ('RIFIUTATA', 'Rifiutata')], default='RICHIESTA', max_length=20)),
                ('prezzo', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('pagata', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, null=True)),
                ('studente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lezioni', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Lezioni',
                'ordering': ['-data_inizio'],
            },
        ),
    ]
