# Generated by Django 6.0 on 2025-12-05 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lezione',
            name='data_inizio',
            field=models.DateTimeField(help_text='Giorno e ora inizio'),
        ),
        migrations.AlterField(
            model_name='lezione',
            name='durata_ore',
            field=models.DecimalField(decimal_places=1, default=1.0, help_text="Durata in ore (es. 1.5 per un'ora e mezza)", max_digits=3),
        ),
        migrations.AlterField(
            model_name='lezione',
            name='luogo',
            field=models.CharField(choices=[('BASE', '🏠 Online / Casa Mia (Tariffa Base)'), ('RUFINA', '🚶 Rufina Paese (+2€)'), ('FASCIA_15', '🚗 Entro 15 min - Montebonello/Scopeti/Pomino (+4€)'), ('FASCIA_30', '🚗 Entro 30 min - Pontassieve/Sieci/Dicomano/Londa (+8€)'), ('ALTRO', '❓ Altro (Contattami)')], default='BASE', max_length=20),
        ),
    ]
