# Generated by Django 5.1.4 on 2025-12-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_lezione_data_inizio_alter_lezione_durata_ore_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disponibilita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giorno', models.IntegerField(choices=[(0, 'Lunedì'), (1, 'Martedì'), (2, 'Mercoledì'), (3, 'Giovedì'), (4, 'Venerdì'), (5, 'Sabato'), (6, 'Domenica')], unique=True)),
                ('ora_inizio', models.TimeField(help_text='Ora di inizio disponibilità (es. 14:30)')),
                ('ora_fine', models.TimeField(help_text='Ora di fine disponibilità (es. 19:00)')),
            ],
            options={
                'verbose_name_plural': 'Disponibilità',
                'ordering': ['giorno'],
            },
        ),
        migrations.AlterField(
            model_name='lezione',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
