# Generated by Django 5.1.4 on 2025-12-12 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_disponibilita_id_alter_lezione_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profilo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, help_text='Utile per urgenze (WhatsApp)', max_length=20, null=True)),
                ('indirizzo', models.CharField(blank=True, help_text='Indirizzo completo (se vengo io da te)', max_length=255, null=True)),
                ('scuola', models.CharField(blank=True, help_text='Es. Liceo Scientifico, 4° Anno', max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profilo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
