# Generated by Django 5.1.4 on 2025-12-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_profilo'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiornoChiusura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(help_text='Giorno in cui non fai lezione', unique=True)),
                ('motivo', models.CharField(blank=True, help_text='Es. Vacanze di Natale', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Giorni di Chiusura',
                'ordering': ['data'],
            },
        ),
    ]
