# Generated by Django 5.1.4 on 2025-12-12 14:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_giornochiusura'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='giornochiusura',
            options={'ordering': ['-data_inizio'], 'verbose_name_plural': 'Giorni di Chiusura'},
        ),
        migrations.AlterModelOptions(
            name='profilo',
            options={'verbose_name_plural': 'Profili'},
        ),
        migrations.RemoveField(
            model_name='giornochiusura',
            name='data',
        ),
        migrations.AddField(
            model_name='giornochiusura',
            name='data_fine',
            field=models.DateField(blank=True, help_text='Ultimo giorno di chiusura', null=True),
        ),
        migrations.AddField(
            model_name='giornochiusura',
            name='data_inizio',
            field=models.DateField(default=django.utils.timezone.now, help_text='Primo giorno di chiusura'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='giornochiusura',
            name='motivo',
            field=models.CharField(blank=True, help_text='Es. Vacanze Estive', max_length=100),
        ),
    ]
