# Generated by Django 5.1.4 on 2025-12-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_giornochiusura_options_alter_profilo_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Impostazioni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tariffa_base', models.DecimalField(decimal_places=2, default=10.0, help_text="Prezzo all'ora base", max_digits=5)),
            ],
            options={
                'verbose_name_plural': 'Impostazioni',
            },
        ),
    ]
