# Generated by Django 5.1.4 on 2026-02-14 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_impostazioni'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilo',
            name='tariffa_specifica',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Se impostata, questa tariffa vince su quella globale.', max_digits=5, null=True),
        ),
    ]
