# Generated by Django 5.1.4 on 2026-09-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_profilo_tariffa_specifica'),
    ]

    operations = [
        migrations.AddField(
            model_name='lezione',
            name='materia',
            field=models.CharField(blank=True, help_text='Es. Matematica, Fisica (anche più di una)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lezione',
            name='durata_ore',
            field=models.DecimalField(decimal_places=1, default=1.0, help_text='Durata in ore (minimo 1h, poi ogni 0.5h)', max_digits=3),
        ),
        migrations.AlterField(
            model_name='lezione',
            name='stato',
            field=models.CharField(choices=[('RICHIESTA', 'In attesa di conferma'), ('CONFERMATA', 'Confermata'), ('RIFIUTATA', 'Rifiutata'), ('CANCELLATA', 'Cancellata dallo studente')], default='RICHIESTA', max_length=20),
        ),
    ]
